apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-panel-configmap-integration
  namespace: ops-panel
data:
  GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
  CONSUMER: '{{ .Values.pubsub.topics.consumer }}'
  PRODUCER: '{{ .Values.pubsub.topics.producer }}'
  PROJECT_ID: '{{ .Values.gcp.projectId }}'
  ENV: int

