apiVersion: v1
kind: ConfigMap
metadata:
  name: ap008-bk-conciliation-configmap-staging
  namespace: ap008-bk-conciliation
data:
  GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
  CONSUMER:  '{{ .Values.pubsub.topics.consumer }}'
  PRODUCER: '{{ .Values.pubsub.topics.producer }}'
  PROJECT_ID: '{{ .Values.gcp.projectId }}'
  ENV: stg
