# Default values for controlbase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/cerc2-datalake-stg-01/ops-panel
  tag: '19433'
  pullPolicy: IfNotPresent

nameOverride: 'ops-panel'
fullnameOverride: 'ops-panel'

service:
  port: 80
  containerPort: 8080

credential:
  path: /var/secrets/google/

gcp:
  serviceAccount: datalake-stg-sa-bookkeeping-01
  setupServiceAccount: true
  projectId: cerc2-book-stg-01

requests:
  cpu: '400m'
  memory: '1800Mi'

autoscaling:
  minReplicas: 1
  maxReplicas: 500
  targetCPUUtilizationPercentage: 10

imagePullSecrets: []

environment: staging

pubsub:
  topics:
    consumer: 'transaction.new'
    producer: ''


