# Default values for controlbase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/cerc2-datalake-int-01/ap008-bk-conciliation
  tag: '19433'
  pullPolicy: IfNotPresent

gcp:
  serviceAccount: datalake-int-sa-bookkeeping-01
  setupServiceAccount: true
  projectId: cerc2-book-int-01

requests:
  cpu: '400m'
  memory: '1800Mi'

autoscaling:
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 10

pubsub:
  topics:
    consumer: 'transaction.new'
    producer: ''