apiVersion: v1
kind: Secret
metadata:
  name: ops-panel-secrets
  namespace: ops-panel
  labels:
    application: ops-panel
    chart: ops-panel
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ops-panel-key: {{ .Values.googleCredentials | quote }}