apiVersion: v1
kind: Secret
metadata:
  name: ap008-bk-conciliation-secrets
  namespace: ap008-bk-conciliation
  labels:
    application: ap008-bk-conciliation
    chart: ap008-bk-conciliation
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ap008-bk-conciliation-key: {{ .Values.googleCredentials | quote }}