{{- if .Values.gcp.setupServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gcp.serviceAccount }}
  namespace: ops-panel
  annotations:
    "iam.gke.io/gcp-service-account": "{{ .Values.gcp.serviceAccount }}@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com"
  {{- end }}