apiVersion: v1
kind: Service
metadata:
  name: ops-panel-service
  namespace: ops-panel
spec:
  type: LoadBalancer
  selector:
    app: ops-panel
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http

---

apiVersion: v1
kind: Service
metadata:
  name: ops-panel-service-private
  namespace: ops-panel
  annotations:
    cloud.google.com/load-balancer-type: "Internal"  
spec:
  type: LoadBalancer
  selector:
    app: ops-panel
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http